consult/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

# handler404 = 'main.views.error'

urlpatterns = [
    path('myconsult/admin/page/', admin.site.urls),
    path('', include('main.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views as v

app_name = 'main'

urlpatterns = [
    path('', v.HomeView.as_view(), name='home'),
    path('detail/<int:id>/', v.Detail.as_view(), name='detail')
]

templates/detail.html
{% extends 'home.html' %}
{% load static %}
{% block title %}

{% endblock %}
    {% block logo %}
    
      {% if logo %}
        <img src="{{logo.logo.url}}" alt="logo yoq">
      {% else %}
        INEX
      {% endif %}

    {% endblock %}


{% block content %}

    <!-- Hero Section -->
    <section  class=" dark-background">


    </section><!-- /Hero Section -->
   
        <!-- Page Title -->
        <div class="page-title" data-aos="fade">
          <div class="container">
            <nav class="breadcrumbs">
              <ol>
                <li><a href="{% url 'main:home' %}">Бош саҳифа</a></li>
                <li class="current">Фаолият тури</li>
              </ol>
            </nav>
            <h1>Фаолият тури</h1>
          </div>
        </div><!-- End Page Title -->
    
        <!-- Portfolio Details Section -->
        <section id="portfolio-details" class="portfolio-details section">
    
          <div class="container" data-aos="fade-up" data-aos-delay="100">
    
            <div class="row gy-4">
    
              <div class="col-lg-5">
                <div class="portfolio-details-slider swiper init-swiper">
    
                  <script type="application/json" class="swiper-config">
                    {
                      "loop": true,
                      "speed": 600,
                      "autoplay": {
                        "delay": 5000
                      },
                      "slidesPerView": "auto",
                      "pagination": {
                        "el": ".swiper-pagination",
                        "type": "bullets",
                        "clickable": true
                      }
                    }
                  </script>
    
                  <div class="swiper-wrapper align-items-center">
                    {% if one.photos.exists %}
                    {% for i in one.photos.all %}
                    <div class="swiper-slide">
                      <img src="{{i.photo.url}}" alt="">
                    </div>
                    {% endfor %}
                    {% else %}
    
                    <div class="swiper-slide">
                      <img src="{{one.activity_photo.url}}" alt="">
                    </div>
                    {% endif %}
    
                  </div>
                  <div class="swiper-pagination"></div>
                </div>
              </div>
    
              <div class="col-lg-7">
                <div class="portfolio-info" data-aos="fade-up" data-aos-delay="200">
                  <h3>{{one.activity_name}}</h3>
                </div>
                <div class="portfolio-description" data-aos="fade-up" data-aos-delay="300">
                  <!-- <h2>Exercitationem repudiandae officiis neque suscipit</h2> -->
                  <p>
               {{one.activity_description}}
                  </p>
                </div>
              </div>
    
            </div>
    
          </div>
    
        </section><!-- /Portfolio Details Section -->
    
  

{% endblock %}

  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-lg-6">
            <!-- <h4>Join Our Newsletter</h4>
            <p>Subscribe to our newsletter and receive the latest news about our products and services!</p> -->
            <!-- <form action="forms/newsletter.php" method="post" class="php-email-form"> -->
              <!-- <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div> -->
              <!-- <div class="loading">Loading</div> -->
              <!-- <div class="error-message"></div> -->
              <!-- <div class="sent-message">Your subscription request has been sent. Thank you!</div> -->
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="d-flex align-items-center">
            <span class="sitename">INEXCONSULTING</span>
          </a>
          <div class="footer-contact pt-3">
            <p>Toшкент, Юнусобод, 10-yй</p>
            <!-- <p>New York, NY 535022</p> -->
            <p class="mt-3"><strong>Телефон:</strong> <span>+998 90 900 5776</span></p>
            <p><strong>Електрон манзил:</strong> <span>info@example.com</span></p>
          </div>
        </div>

        <!-- <div class="col-lg-2 col-md-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
          </ul>
        </div> -->

        <!-- <div class="col-lg-2 col-md-3 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
            <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
          </ul>
        </div> -->

        <div class="col-lg-4 col-md-12">
          <h4>Follow Us</h4>
          <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
          <div class="social-links d-flex">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-telegram"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">INEXCONSULTING</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        <!-- Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
      </div>
    </div>

  </footer>

templates/error.html
{% extends 'home.html' %}
{% load static %}
{% block title %}

{% endblock %}
    {% block logo %}
    
      {% if logo %}
        <img src="{{logo.logo.url}}" alt="logo yoq">
      {% else %}
        INEX
      {% endif %}

    {% endblock %}

{% block content %}
<section  class=" dark-background">


</section><!-- /Hero Section -->

  <!-- Portfolio Details Section -->
  <section id="portfolio-details" class="portfolio-details section">
    
    <div class="container" data-aos="fade-up" data-aos-delay="100">

      <div class="row gy-4">

        <div class="col-lg-5">
          <div class="portfolio-details-slider swiper init-swiper">
            <div class="swiper-wrapper align-items-center">

              <div class="swiper-slide">
                <img src="{% static 'assets/img/error/error.jpg' %}" alt="">
              </div>

            </div>
          </div>
        </div>

        <div class="col-lg-7">
          <div class="portfolio-info" data-aos="fade-up" data-aos-delay="200">
            <h1>Саҳифа топилмади ! ! !</h1>
            <ul>
              <li>
                <h2>
                    <a href="{% url 'main:home' %}" style="font-family: 'Times New Roman', Times, serif;">

                        <strong>  Бош саҳифа га қайтиш </strong>
                    </a>
                </h2>

                </li>

            </ul>
          </div>

        </div>

      </div>

    </div>

  </section><!-- /Portfolio Details Section -->


{% endblock %}

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
 
    <title>
        INEXCONSULTING
        {% block title %}

        {% endblock %}
    </title>
 
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  {% block headlogo %}

  {% endblock %}
  <!-- <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon"> -->

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Arsha
  * Template URL: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">

      <a href="{% url 'main:home' %}" class="logo d-flex align-items-center me-auto">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">
            {% block logo %}

            {% endblock %}
        </h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'main:home' %}" class="active">Бош саҳифа</a></li>
          <li><a href="{% url 'main:home' %}#about">Компания ҳaқида</a></li>
          <li><a href="{% url 'main:home' %}#services">Фаолият турлари</a></li>
          
          <li><a href="{% url 'main:home' %}#team"> Жамоа</a></li>
          
          <li><a href="{% url 'main:home' %}#contact">Боғланиш</a></li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

      <!-- <a class="btn-getstarted" href="#about">Get Started</a> -->

    </div>
  </header>

  <main class="main">

    {% block content %}



    {% endblock %}



  </main>

 {% block footer %}
 {% endblock  %}

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- <script src="assets/vendor/php-email-form/validate.js"></script> -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>